export const DEFAULTS = {
  RATE_LIMIT_MAX_SKEW: 300,
  RATE_LIMIT_MIN_SKEW: 30,
  RATE_LIMIT_MAX: 5,
  RATE_LIMIT_WINDOW_MS: 60_000,
  WANOTIFIER_HMAC_HEADER: 'x-signature',
  WANOTIFIER_TS_HEADER: 'x-timestamp',
  MEMORY_TTL_HOURS: 24,
  MEMORY_MAX_MESSAGES: 20,
  MEMORY_MAX_CONVERSATIONS: 5000,
  MAX_WA_REPLY_CHARS: 4000,
};
