import dotenv from 'dotenv';
import { DEFAULTS } from './constants.js';

dotenv.config();

export function loadEnv(env) {
  return {
    PORT: env.PORT,
    OPENAI_API_KEY: env.OPENAI_API_KEY || '',
    OPENAI_MODEL: env.OPENAI_MODEL || '',
    OPENAI_STT_MODEL: env.OPENAI_STT_MODEL || '',
    OPENAI_STT_DARIJA_PROMPT: env.OPENAI_STT_DARIJA_PROMPT || '',
    OFFERS_REFRESH_MS: Number(env.OFFERS_REFRESH_MS || 0),
    OFFERS_REFRESH_TOKEN: env.OFFERS_REFRESH_TOKEN || '',
    WC_BASE_URL: env.WC_BASE_URL || '',
    WC_CONSUMER_KEY: env.WC_CONSUMER_KEY || '',
    WC_CONSUMER_SECRET: env.WC_CONSUMER_SECRET || '',
    WC_PER_PAGE: Number(env.WC_PER_PAGE || 0),
    WC_STATUS: env.WC_STATUS || '',
    ORDER_FORM_URL: env.ORDER_FORM_URL || '',
    RATE_LIMIT_WINDOW_MS: Number(env.RATE_LIMIT_WINDOW_MS || DEFAULTS.RATE_LIMIT_WINDOW_MS),
    RATE_LIMIT_MAX: Number(env.RATE_LIMIT_MAX || DEFAULTS.RATE_LIMIT_MAX),
    MEMORY_TTL_HOURS: Number(env.MEMORY_TTL_HOURS || DEFAULTS.MEMORY_TTL_HOURS),
    MEMORY_MAX_MESSAGES: Number(env.MEMORY_MAX_MESSAGES || DEFAULTS.MEMORY_MAX_MESSAGES),
    MEMORY_PERSIST: env.MEMORY_PERSIST === 'true' || env.MEMORY_PERSIST === true,
    MEMORY_DIR: env.MEMORY_DIR || '',
    FOCUS_BRAND: env.FOCUS_BRAND || '',
    FOCUS_MODE: env.FOCUS_MODE || '',
    MAX_WA_REPLY_CHARS: Number(env.MAX_WA_REPLY_CHARS || DEFAULTS.MAX_WA_REPLY_CHARS),
    WANOTIFIER_TOKEN: env.WANOTIFIER_TOKEN || '',
    WANOTIFIER_HMAC_SECRET: env.WANOTIFIER_HMAC_SECRET || '',
    WANOTIFIER_HMAC_HEADER: env.WANOTIFIER_HMAC_HEADER || DEFAULTS.WANOTIFIER_HMAC_HEADER,
    WANOTIFIER_TS_HEADER: env.WANOTIFIER_TS_HEADER || DEFAULTS.WANOTIFIER_TS_HEADER,
    WANOTIFIER_MAX_SKEW_SECONDS: Math.max(
      DEFAULTS.WANOTIFIER_MIN_TS_SKEW_SECONDS,
      Number(env.WANOTIFIER_MAX_SKEW_SECONDS || DEFAULTS.WANOTIFIER_MAX_TS_SKEW_SECONDS),
    ),
    LOG_DEBUG: env.LOG_DEBUG === 'true' || env.LOG_DEBUG === true,
  };
}
