// Category keywords, class mappings, and related constants

export const TV_CLASS_SYNONYMS = Object.freeze([
  "tv",
  "tele",
  "télé",
  "television",
  "télévision",
  "televiseur",
  "téléviseur",
  "smart tv",
  "android tv",
  "google tv",
  "تلفاز",
  "تلفزة",
  "تلفزيون",
  "تيليفزيون",
]);

export const TV_TITLE_HINTS = Object.freeze([
  "tv",
  "smart tv",
  "android tv",
  "google tv",
  "oled",
  "qled",
  "mini led",
  "mini-led",
  "4k",
  "uhd",
  "led",
  "tele",
  "télé",
  "television",
  "télévision",
  "تلفاز",
  "تلفزيون",
]);

export const BRAND_ONLY_CATEGORY_KEYWORDS = Object.freeze([
  "tv",
  "tele",
  "télé",
  "television",
  "télévision",
  "téléviseur",
  "smart tv",
  "android tv",
  "oled",
  "qled",
  "4k",
  "frigo",
  "refrigerateur",
  "réfrigérateur",
  "congelateur",
  "congélateur",
  "ثلاجة",
  "فريكو",
  "clim",
  "climatiseur",
  "مكيف",
  "كليم",
  "machine",
  "lave linge",
  "lave-linge",
  "غسالة",
  "déshumidificateur",
  "deshumidificateur",
  "مزيل الرطوبة",
]);

export const BRAND_ONLY_OK_TOKENS = Object.freeze([
  "option",
  "options",
  "choix",
  "selection",
  "sélection",
  "catalog",
  "catalogue",
  "liste",
  "list",
  "menu",
  "show",
  "display",
  "prix",
  "price",
  "promo",
  "promotion",
  "promos",
  "offre",
  "offres",
  "offer",
  "offers",
  "deal",
  "deals",
  "discount",
  "sale",
  "soldes",
  "svp",
  "stp",
  "please",
  "pls",
  "dyal",
  "dial",
  "diall",
]);

export const CATEGORY_ALIASES = Object.freeze({
  Tv: [
    "tv",
    "tele",
    "télé",
    "television",
    "télévision",
    "تلفاز",
    "تلفزة",
    "تلفزيون",
    "ecran",
    "écran",
    "lcran",
  ],
  Climatiseur: [
    "clim",
    "climatiseur",
    "climatiseur mobile",
    "climatisation",
    "air conditioner",
    "ac",
    "مكيف",
    "مكيف هواء",
    "klima",
    "كليما",
  ],
  "Machine A Laver": [
    "machine a laver",
    "machine à laver",
    "machine a laver le linge",
    "machine à laver le linge",
    "lave linge",
    "lave-linge",
    "lavelinge",
    "washing machine",
    "ماكينة صابون",
    "غسالة",
    "غسالة ملابس",
    "غسالة ديال الحوايج",
    "غسالة ديال لوايج",
    "ماكينة اوتوماتيك",
    "ماكينة أوتوماتيك",
    "ماكينة اوطوماتيك",
    "ماكينة أوطوماتيك",
    "ماكينة اتوماتيك",
    "مكينة اوتوماتيك",
    "مكينة اوطوماتيك",
    "مكينة اتوماتيك",
    "mquina dial ssiab",
    "mquina dyal ssiab",
    "machina dial ssiab",
    "machine automatique",
    "lave linge automatique",
  ],
  Refrigerateur: [
    "refrigerateur",
    "réfrigérateur",
    "refrigerator",
    "frigo",
    "frigidaire",
    "ريفريجيراتور",
    "ثلاجة",
    "ثلاج",
    "تلاجة",
    "لاجة",
    "براد",
    "refrigirateur",
    "talaja",
    "tlaja",
    "thalaja",
    "thallaja",
    "thallajat",
    "telajja",
    "friko",
    "فريكو",
  ],
  Congelateur: ["congelateur", "congélateur", "freezer", "فريزر"],
  "Chauffe-eau": ["chauffe-eau", "chauffe eau", "water heater", "سخان"],
  "Micro-ondes": ["micro-ondes", "micro ondes", "micro onde", "microondes", "microonde", "microwave", "ميكرو"],
  "Lave Vaisselle": ["lave vaisselle", "lave-vaisselle", "lavevaisselle", "dishwasher", "غسالة صحون"],
  "Air Fryer": ["air fryer", "airfryer", "قلاية هوائية", "اير فراير", "ايرفراير"],
  "Barre De Son": ["barre de son", "soundbar", "ساندبار"],
  Cuisiniere: [
    "cuisiniere",
    "cuisinière",
    "cuisinier",
    "gaziniere",
    "gazinière",
    "four",
    "forn",
    "فران",
    "فورنو",
    "طباخة",
    "موقد",
    "بوتاجاز",
    "kuzina",
    "kouzina",
    "kوزينة",
    "كوزينة",
    "كوجينة",
    "cuisinière gaz",
    "cuisson",
    "cuisine",
    "cooker",
    "stove",
    "range",
  ],
});

export const APPLIANCE_CATEGORY_KEYWORDS = Object.freeze({
  cooker: CATEGORY_ALIASES.Cuisiniere,
  refrigerator: CATEGORY_ALIASES.Refrigerateur,
  washing_machine: CATEGORY_ALIASES["Machine A Laver"],
  air_conditioner: CATEGORY_ALIASES.Climatiseur,
  microwave: CATEGORY_ALIASES["Micro-ondes"],
  dishwasher: CATEGORY_ALIASES["Lave Vaisselle"],
  water_heater: CATEGORY_ALIASES["Chauffe-eau"],
});

export const APPLIANCE_CATEGORY_CANON = Object.freeze({
  cooker: "Cuisiniere",
  refrigerator: "Refrigerateur",
  washing_machine: "Machine A Laver",
  air_conditioner: "Climatiseur",
  microwave: "Micro-ondes",
  dishwasher: "Lave Vaisselle",
  water_heater: "Chauffe-eau",
});

export const CATEGORY_CLASS_KEYWORDS = Object.freeze([
  {
    category: "Refrigerateur",
    keywords: [
      "ثلاجة",
      "ثلاج",
      "تلاجة",
      "لاجة",
      "fridge",
      "frigo",
      "frigidaire",
      "réfrigérateur",
      "refrigerator",
      "refrigerateur",
      "refrigirateur",
      "no frost",
      "nofrost",
      "نو فروست",
      "نو فرست",
      "talaja",
      "tlaja",
      "thalaja",
      "thallaja",
      "thallajat",
      "telajja",
      "friko",
      "فريكو",
      "براد",
    ],
  },
  {
    category: "Tv",
    cls: "Tv",
    keywords: [
      "تلفاز",
      "تلفزة",
      "تلفزيون",
      "tv",
      "télé",
      "tele",
      "télévision",
      "television",
      "smart tv",
      "android tv",
      "google tv",
      "oled",
      "qled",
      "ecran",
      "écran",
      "lcran",
    ],
  },
  {
    category: "Machine A Laver",
    keywords: [
      "غسالة",
      "غسالة ملابس",
      "غسالة ديال الحوايج",
      "غسالة ديال لوايج",
      "lavage",
      "machine a laver",
      "machine à laver",
      "machine a laver le linge",
      "machine à laver le linge",
      "lave linge",
      "lave-linge",
      "lavelinge",
      "washing machine",
      "machina dial ssiab",
      "mquina dial ssiab",
      "mquina dyal ssiab",
      "ماكينة اوتوماتيك",
      "ماكينة أوتوماتيك",
      "ماكينة اوطوماتيك",
      "ماكينة أوطوماتيك",
      "ماكينة اتوماتيك",
      "مكينة اوتوماتيك",
      "مكينة اوطوماتيك",
      "مكينة اتوماتيك",
      "machine automatique",
      "lave linge automatique",
    ],
  },
  {
    category: "Climatiseur",
    keywords: [
      "مكيف",
      "مكيف هواء",
      "مكيف هوائي",
      "climatiseur",
      "clim",
      "climatisation",
      "climatiseur mobile",
      "air conditioner",
      "ac",
      "klima",
      "كليما",
    ],
  },
  {
    category: "Cuisiniere",
    keywords: [
      "cuisiniere",
      "cuisinière",
      "cuisinier",
      "gaziniere",
      "gazinière",
      "four",
      "forn",
      "فران",
      "فورنو",
      "طباخة",
      "موقد",
      "بوتاجاز",
      "kuzina",
      "kouzina",
      "kوزينة",
      "كوزينة",
      "كوجينة",
      "cuisinière gaz",
      "cuisson",
      "cuisine",
      "cooker",
      "stove",
      "range",
    ],
  },
  {
    category: "Micro-ondes",
    keywords: ["micro-ondes", "micro ondes", "micro onde", "microondes", "microonde", "microwave", "ميكرو"],
  },
  {
    category: "Lave Vaisselle",
    keywords: ["lave vaisselle", "lave-vaisselle", "lavevaisselle", "dishwasher", "غسالة صحون"],
  },
  {
    category: "Chauffe-eau",
    keywords: ["chauffe-eau", "chauffe eau", "water heater", "سخان"],
  },
]);
